# Generated by Django 5.2.3 on 2025-06-22 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Введите дату и время первой отправки', verbose_name='Дата и время первой отправки')),
                ('end_datetime', models.DateTimeField(help_text='Введите дату и время окончания отправки', verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('Created', 'Создана'), ('Running', 'Запущена'), ('Completed', 'Завершена')], default='Created', help_text='Статус рассылки', max_length=10, verbose_name='Статус')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_send_data', models.DateTimeField(auto_now=True, verbose_name='Дата и время попытки')),
                ('attempt_status', models.CharField(choices=[('Success', 'Успешно'), ('Failed', 'Не успешно')], default='Success', max_length=10)),
                ('answer', models.TextField(verbose_name='Ответ почтового сервера')),
                ('Mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите Ф.И.О. получателя', max_length=100, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(help_text='Введите комментарий', verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылок',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipient',
            field=models.ManyToManyField(to='mailer.mailingrecipient', verbose_name='Получатели'),
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему письма', max_length=50, verbose_name='Тема письма')),
                ('content', models.TextField(help_text='Введите текст письма', verbose_name='Тело письма')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.mailmessage'),
        ),
    ]
