# Generated by Django 5.2.3 on 2025-07-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Введите дату и время первой отправки', verbose_name='Дата и время первой отправки')),
                ('end_datetime', models.DateTimeField(help_text='Введите дату и время окончания отправки', verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('Created', 'Создана'), ('Launched', 'Запущена'), ('Completed', 'Завершена')], default='Created', help_text='Статус рассылки', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['id'],
                'permissions': [('can_view_mailing', 'Can view mailing')],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_send_data', models.DateTimeField(auto_now=True, verbose_name='Дата и время попытки')),
                ('attempt_status', models.CharField(choices=[('Success', 'Успешно'), ('Failed', 'Не успешно')], default='Success', max_length=10)),
                ('answer', models.TextField(verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите Ф.И.О. получателя', max_length=100, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(help_text='Введите комментарий', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылок',
                'ordering': ['id'],
                'permissions': [('can_view_recipient', 'Can view recipient')],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему письма', max_length=50, verbose_name='Тема письма')),
                ('content', models.TextField(help_text='Введите текст письма', verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
                'permissions': [('can_view_message', 'Can view message')],
            },
        ),
    ]
