# Generated by Django 5.2.3 on 2025-07-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='Mailing',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Created', 'Создана'), ('Launched', 'Запущена'), ('Completed', 'Завершена')], default='Created', help_text='Статус рассылки', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.mailing', verbose_name='Рассылка'),
        ),
    ]
